autoscalingGroups:
- maxSize: 10
  minSize: 1
  name: srii-general-20220731231227380200000019
- maxSize: 0
  minSize: 0
  name: srii-runners-2022073123122738240000001a
rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::373346310182:role/delegatedadmin/developer/cluster-autoscaler
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: "0.5"
    memory: 500m
tolerations:
- effect: NoSchedule
  key: CriticalAddonsOnly
  operator: Exists